import Image from "next/image";
import Link from "next/link";
import { DemoMintCard } from "@/components/DemoMintCard";
import { mockCollection } from "@/data/mock-collection";

const panel = "bg-white/[0.03] backdrop-blur-xl border border-white/[0.08] shadow-[0_8px_32px_0_rgba(0,0,0,0.37)]";
export default function Home() {
  return <main className="premium-canvas min-h-screen overflow-hidden text-white">
    <header className="sticky top-0 z-40 border-b border-white/[0.08] bg-black/30 backdrop-blur-2xl">
      <nav className="mx-auto flex h-20 max-w-7xl items-center justify-between px-6 lg:px-10" aria-label="Main navigation">
        <Link href="/" className="flex items-center gap-3"><span className="grid h-9 w-9 place-items-center rounded-xl border border-white/15 bg-white/[.04] text-emerald-300">A</span><span className="font-semibold tracking-tight">Alien<span className="text-white/40">Mint</span></span></Link>
        <div className="flex items-center gap-2"><span className="hidden rounded-full border border-emerald-400/20 bg-emerald-400/[.06] px-3 py-2 text-xs text-emerald-200 sm:block">Interactive Demo</span><Link href="/studio" className="interactive-control rounded-full px-4 py-2 text-sm">Creator Studio</Link><Link href="/live" className="interactive-control hidden rounded-full px-4 py-2 text-sm sm:block">Live testnet</Link></div>
      </nav>
    </header>
    <section className="relative mx-auto grid max-w-7xl items-center gap-14 px-6 py-16 lg:grid-cols-[1.05fr_.95fr] lg:px-10 lg:py-24">
      <div><div className="clear-pill mb-7 inline-flex items-center gap-2 px-4 py-2 text-xs uppercase tracking-[.18em] text-emerald-200"><span className="h-2 w-2 rounded-full bg-emerald-400"/>No wallet required</div><h1 className="text-balance text-5xl font-medium leading-[.98] tracking-[-.05em] sm:text-7xl">Digital objects,<br/><span className="text-gradient">made permanent.</span></h1><p className="mt-7 max-w-xl text-lg leading-8 text-white/52">{mockCollection.description}</p><div className="clear-rail mt-10 grid max-w-xl grid-cols-3">{[["10K","Edition"],["0.05 ETH","Demo price"],["ERC721A","Standard"]].map(x=><div className="stat-item px-4 py-4" key={x[1]}><p className="font-medium">{x[0]}</p><p className="mt-1 text-[10px] uppercase tracking-widest text-white/35">{x[1]}</p></div>)}</div></div>
      <DemoMintCard />
    </section>
    <section id="collection" className="mx-auto max-w-7xl px-6 py-20 lg:px-10"><p className="text-xs uppercase tracking-[.25em] text-cyan-300">Selected works</p><h2 className="mt-4 text-3xl tracking-tight sm:text-5xl">A coherent visual collection.</h2><div className="mt-10 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{mockCollection.artworks.map(([src,name,trait],i)=><article key={src} className={`${panel} group overflow-hidden rounded-[1.5rem]`}><div className="relative aspect-square overflow-hidden"><Image src={src} alt={`${name}, a glass sculpture from AlienMint Genesis`} fill sizes="(max-width: 768px) 100vw, 33vw" className="object-cover transition duration-700 group-hover:scale-[1.03]"/></div><div className="flex items-end justify-between p-5"><div><h3 className="font-medium">{name}</h3><p className="mt-1 text-sm text-white/40">Alien #{3428+i}</p></div><span className="text-xs text-emerald-200/70">{trait}</span></div></article>)}</div></section>
    <section className="mx-auto grid max-w-7xl gap-5 px-6 py-20 lg:grid-cols-3 lg:px-10">{[["Auditable by design","ERC721A contract, exact pricing, fixed maximum supply."],["Portable metadata","Each token maps to a standard ERC-721 metadata document."],["Production pathway","The live Base Sepolia build is preserved for technical review."]].map(x=><article className={`${panel} rounded-3xl p-7`} key={x[0]}><div className="mb-8 h-1 w-10 rounded bg-gradient-to-r from-emerald-400 to-cyan-400"/><h3 className="text-xl">{x[0]}</h3><p className="mt-3 leading-7 text-white/45">{x[1]}</p></article>)}</section>
    <section className="mx-auto max-w-4xl px-6 py-20"><h2 className="text-3xl">Mint FAQ</h2><div className="mt-8 divide-y divide-white/[.08] border-y border-white/[.08]">{[["Is this a real transaction?","No. The homepage is an explicitly simulated approval demo; no wallet or funds are used."],["Can I inspect the Web3 version?","Yes. Open the live testnet route to review wallet, network, contract reads, and transaction states."],["How is creator artwork added?","Use Creator Studio to select and order images locally, define metadata, and preview the publishing pipeline."]].map(x=><details className="group py-6" key={x[0]}><summary className="cursor-pointer list-none font-medium">{x[0]} <span className="float-right text-white/35">+</span></summary><p className="mt-4 max-w-2xl leading-7 text-white/45">{x[1]}</p></details>)}</div></section>
    <footer className="border-t border-white/[.08]"><div className="mx-auto flex max-w-7xl flex-col justify-between gap-4 px-6 py-10 text-sm text-white/35 sm:flex-row lg:px-10"><p>AlienMint — interactive product demonstration.</p><div className="flex gap-5"><Link href="/studio">Creator Studio</Link><Link href="/live">View live testnet version</Link></div></div></footer>
  </main>;
}
