import { readFile, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const artifactPath = resolve(root, '../contracts/out/NFTCollection.sol/NFTCollection.json');
const outputPath = resolve(root, 'src/config/abi.ts');
const artifact = JSON.parse(await readFile(artifactPath, 'utf8'));
const output = `// Generated by npm run abi:generate. Do not edit manually.\n` +
  `export const abi = ${JSON.stringify(artifact.abi, null, 2)} as const;\n`;

if (process.argv.includes('--check')) {
  const current = await readFile(outputPath, 'utf8').catch(() => '');
  if (current !== output) {
    throw new Error('Contract ABI is stale. Run npm run abi:generate.');
  }
} else {
  await writeFile(outputPath, output);
}
